# Generated by Django 5.0.4 on 2024-04-05 23:43

import single_blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_blog', '0003_alter_comment_options_comment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PostImg',
            field=models.ImageField(default=1, upload_to=single_blog.models.GetImageUploadTo),
            preserve_default=False,
        ),
    ]
